### ISSUE TITLE
debugging warnings when creating a new assignment

### ISSUE THREAD

**Issue by danmarsden** [mattan-d/moodle-plagiarism_originality#10]
When I create a new assignment, I'm seeing these debugging errors on the page:

Warning: Attempt to read property "id" on null in /moodle/plagiarism/originality/lib.php on line 747

Warning: Undefined property: stdClass::$default_use in /moodle/plagiarism/originality/lib.php on line 763

**Comment by danmarsden** [comment]
when I save the same page, I get the following warnings too:


Warning: Undefined variable $cm in plagiarism/originality/lib.php on line 747

Warning: Attempt to read property "id" on null in plagiarism/originality/lib.php on line 747

Warning: Undefined property: stdClass::$default_use in plagiarism/originality/lib.php on line 763

Warning: Undefined property: stdClass::$originality_use_ghostwriter in plagiarism/originality/lib.php on line 811

**Comment by mattan-d** [comment]
Fix: Resolve debugging errors when creating a new assignment.
