### ISSUE TITLE
debugging warnings when submitting a new assignment file.

### ISSUE THREAD

**Issue by danmarsden** [mattan-d/moodle-plagiarism_originality#11]
When I upload an assignment, I get the following debugging warning from Moodle

Invalid event functions defined in \plagiarism_originality\event\document_submitted
line 275 of /lib/classes/event/base.php: call to debugging()
line 293 of /plagiarism/originality/lib.php: call to core\event\base::create()
line 443 of /plagiarism/originality/lib.php: call to plagiarism_plugin_originality->make_call()
line 378 of /plagiarism/originality/lib.php: call to plagiarism_plugin_originality->originality_event_file_uploaded()
line 67 of /plagiarism/originality/classes/observer.php: call to plagiarism_plugin_originality->originality_event_submitted()
line ? of unknownfile: call to plagiarism_originality_observer::assignsubmission_submitted()
line 155 of /lib/classes/event/manager.php: call to call_user_func()
line 75 of /lib/classes/event/manager.php: call to core\event\manager::process_buffers()
line 795 of /lib/classes/event/base.php: call to core\event\manager::dispatch()
line 7625 of /mod/assign/locallib.php: call to core\event\base->trigger()
line 7660 of /mod/assign/locallib.php: call to assign->save_submission()
line 506 of /mod/assign/locallib.php: call to assign->process_save_submission()
line 55 of /mod/assign/view.php: call to assign->view()

**Comment by danmarsden** [comment]
this one is probably just due to the get_legacy_logdata() function in the  \plagiarism_originality\event\document_submitted class which isn't needed in newer versions of Moodle.

**Comment by mattan-d** [comment]
Fix: Remove unnecessary get_legacy_logdata() function in document_submitted event class.
