### ISSUE TITLE
Hard coded role name 'student'

### ISSUE THREAD

**Issue by danmarsden** [mattan-d/moodle-plagiarism_originality#12]
https://github.com/mattan-d/moodle-plagiarism_originality/blob/3e8516f3f7ce25ad5961400f757683729848af29/lib.php#L73

It would be safer to check a capability here. Some sites will customize the role names so it might even be called 'learner' or some other custom value.

**Comment by mattan-d** [comment]
Improved: Added capability check for customizable role names

**Comment by danmarsden** [comment]
can you remove the call to the shortname == 'student' in the call below too?
https://github.com/mattan-d/moodle-plagiarism_originality/blob/master/lib.php#L77

**Comment by danmarsden** [comment]
.. in fact - that line "shortname == 'student" is causing the view submissions page to hide the originality links from an admin user who also has the "student" role in the course. - they are site admin so should be able to see all the details, but for some reason they also have a "student" role within the course.

**Comment by mattan-d** [comment]
Thank you very much, @danmarsden . That was my mistake.
