### ISSUE TITLE
Get_links function could be more efficient

### ISSUE THREAD

**Issue by danmarsden** [mattan-d/moodle-plagiarism_originality#13]
the function "get_links" can be called multiple times on a single page - particularly when a teacher is viewing a large number of submissions. For this reason you should be implementing some static vars or some level of caching to decrease the amount of work the function needs to do. I have one client that likes showing all users on the submissions page so the function could get called 2000 (or more) times on the single page load.

Things like getting the coursemodule record or stuff related to the currently logged in user should be able to be called once rather than every time the function is called.

This is not a blocker for approval, but also watch out for multiple db calls that could be combined into one db call to get multiple records (like in your get_submissions() function in your util class.)

**Comment by danmarsden** [comment]
one example of static vars (code is a bit messy) but it might be helpful to see how Turnitin does it here:
https://github.com/turnitin/moodle-plagiarism_turnitin/blob/master/lib.php#L677-L680

basically the first time the function is called - it sets $cm, but the 2nd time it's called you already have it stored so you can use the var instead of loading it again using an api/db call.

**Comment by mattan-d** [comment]
Optimized function "get_links" to reduce workload by implementing static variables and caching. Reduced unnecessary calls for retrieving course module records.
