### ISSUE TITLE
is "role" still needed here?

### ISSUE THREAD

**Issue by danmarsden** [mattan-d/moodle-plagiarism_originality#14]
https://github.com/mattan-d/moodle-plagiarism_originality/blob/master/lib.php#L78

is this line still used now you aren't checking the student role? - if not you might be able to remove it :-)

$output->role = current(get_user_roles($PAGE->context, $USER->id));

**Comment by mattan-d** [comment]
In the past, we had a desire to present the report to the student as well. However, this is no longer applicable today.
