### ISSUE TITLE
debugging warning when submitting an assignment

### ISSUE THREAD

**Issue by danmarsden** [mattan-d/moodle-plagiarism_originality#15]
because you've set objecttable to "plagiarism_originality_sub" it's expecting the objectid in the event set to the id of that table in here:

https://github.com/mattan-d/moodle-plagiarism_originality/blob/master/lib.php#L308

Note - you can see these errors yourself if you have developer debugging level set and display errors = on 
---

Full error below:
Event property objectid must be set when objecttable is defined

line 766 of /lib/classes/event/base.php: call to debugging()
line 785 of /lib/classes/event/base.php: call to core\event\base->validate_before_trigger()
line 309 of /plagiarism/originality/lib.php: call to core\event\base->trigger()
line 458 of /plagiarism/originality/lib.php: call to plagiarism_plugin_originality->make_call()
line 393 of /plagiarism/originality/lib.php: call to plagiarism_plugin_originality->originality_event_file_uploaded()
line 67 of /plagiarism/originality/classes/observer.php: call to plagiarism_plugin_originality->originality_event_submitted()
line ? of unknownfile: call to plagiarism_originality_observer::assignsubmission_submitted()
line 155 of /lib/classes/event/manager.php: call to call_user_func()
line 75 of /lib/classes/event/manager.php: call to core\event\manager::process_buffers()
line 795 of /lib/classes/event/base.php: call to core\event\manager::dispatch()
line 7625 of /mod/assign/locallib.php: call to core\event\base->trigger()
line 7660 of /mod/assign/locallib.php: call to assign->save_submission()
line 506 of /mod/assign/locallib.php: call to assign->process_save_

**Comment by mattan-d** [comment]
resolves a debugging warning that occurred during assignment submission.
