### ISSUE TITLE
wrong user var used in check

### ISSUE THREAD

**Issue by danmarsden** [mattan-d/moodle-plagiarism_originality#17]
https://github.com/mattan-d/moodle-plagiarism_originality/blob/master/settings.php#L90

That one should probably be lowercase $user rather than the upper case $USER.

probably just missed when you converted over to using the new user/

**Comment by mattan-d** [comment]
fixes an issue in the settings.php file where the variable "$USER" was incorrectly capitalized. It has been corrected to "$user" for consistency. The issue likely occurred during the transition to using the new user.

**Comment by danmarsden** [comment]
sorry - I should have been more clear - I think this line here that you've also changed to use $user instead of $USER might cause problems:
https://github.com/mattan-d/moodle-plagiarism_originality/blob/master/settings.php#L104

$user - is the new user you have just created, and it doesn't have the "'moodle/webservice:createtoken" capability so that part will always fail.  
higher case $USER - is a special Moodle global var that contains the currently logged in users record.

I think you have a few options there - you could just replace that line with if (!$tokens)) {
or ... just make it:
```
if (!$tokens && has_capability('moodle/webservice:createtoken', context_system::instance())) {
```
Which would basically mean "if a token doesn't exist, and the curernt logged in user (admin) is allowed to create tokens - create one and assign it to the $user we just created.

does that make sense?

**Comment by mattan-d** [comment]
Updated line causing potential issues in the code.
