### ISSUE TITLE
Plugin Ver 7.x: AssignmentCode / MoodleAssignPageNo wrong data

### ISSUE THREAD

**Issue by eliron** [mattan-d/moodle-plagiarism_originality#19]
Our client, UoPeople, has shown me a problem with the Assignment Code appearing on their Originality Report. The number displayed there is incorrect. No such assignment exists. This causes the link to go nowhere (404).

I checked in our database and found out that indeed something is wrong: AssignmentCode and MoodleAssignPageNo have identical data. This is an error. See attached images.

**This is the report**
![Originality with wrong Assignment Code](https://github.com/mattan-d/moodle-plagiarism_originality/assets/1670780/df2a8494-65f3-40ed-8784-8f0f5dc2cff3)

**This is our database**
![image](https://github.com/mattan-d/moodle-plagiarism_originality/assets/1670780/0172fbcd-53fc-4949-8d72-bdd2998a2be4)

The client uses Moodle 4.3
To view the client's DB structure you can use this link: https://www.examulator.com/er/output/tables/assign.html

Thanks,
Eli

**Comment by mattan-d** [comment]
Done.
