### ISSUE TITLE
incorrect table names in install.xml

### ISSUE THREAD

**Issue by danmarsden** [mattan-d/moodle-plagiarism_originality#2]
the tables defined in install.xml are incorrect - plugins must use the frankenstyle naming prefix - this is a plugins db blocker for a number of reasons, including making sure than an uninstall process will work correctly.

Note - table names also have an upper limit/length of 28 characters, so try to keep the table names short - examples of correct table names are "plagiarism_originality_mod" and "plagiarism_orginality_sub"

**Comment by mattan-d** [comment]
Update table names in install.xml to follow the required naming conventions
