### ISSUE TITLE
Plugin 7.x: replace student id with username

### ISSUE THREAD

**Issue by eliron** [mattan-d/moodle-plagiarism_originality#20]
At UoPeople, instructors cannot access the user's details. The client asks to replace the student Id with the field username.
See attached image with student id in a red square.
If done, what is the impact on the REST API (if any)?
If no impact, please make the change.
Thanks
Eli

![image](https://github.com/mattan-d/moodle-plagiarism_originality/assets/1670780/aeed38c9-44ff-4202-86b9-b1b4cc3c9dc2)

**Comment by mattan-d** [comment]
Is the goal to change the value of the ״StudentCode״ variable to your API? [See source code.](https://github.com/mattan-d/moodle-plagiarism_originality/blob/master/lib.php#L280)

https://github.com/mattan-d/moodle-plagiarism_originality/blob/master/lib.php#L280

**Comment by mattan-d** [comment]
Done.

**Comment by eliron** [comment]
**Student code / student name is incorrect.**
Student4 submitted the assignment. However, the name appearing on the report is student3. The link takes us to the Teacher's user page.
[Originality Report with Student Name 2024-01-11.pdf](https://github.com/mattan-d/moodle-plagiarism_originality/files/13898804/Originality.Report.with.Student.Name.2024-01-11.pdf)
![image](https://github.com/mattan-d/moodle-plagiarism_originality/assets/1670780/c3362c92-ebce-4d9f-8ea1-e7b6809a8877)
![image](https://github.com/mattan-d/moodle-plagiarism_originality/assets/1670780/bb942c74-35d0-4cef-9acd-fff97eff5950)

**Comment by eliron** [comment]
Please UNDO the change. Revert to the original student id. There is no point to fix it. Thanks.
