### ISSUE TITLE
incorrect privacy api

### ISSUE THREAD

**Issue by danmarsden** [mattan-d/moodle-plagiarism_originality#3]
You have implemented a null provider privacy api class which is incorrect - your submissions table includes user information which needs to be covered in the privacy api, but you also integrate with an external service, passing user information (email address name etc) to the external service so you need to implement the "add_external_location_link" component, making it clear what information is passed to the external service.

More information on the privacy api is here:
https://moodledev.io/docs/apis/subsystems/privacy

Note - compliance with the privacy api is a blocker for plugins db approval when a plugin integrates with an external service like yours.

**Comment by mattan-d** [comment]
Fix privacy issues and implement "add_external_location_link" component

**Comment by danmarsden** [comment]
Hi @mattan-d - looks like you've missed the delete/export functions required for your mod and sub tables - moodle unit tests will also see that your sub table that contain a userid field and isn't covered in the metadata function and throw unit test failures.

missing the export and delete functions may present a GDPR compliance issue for some organisations too.

my old urkund plugin might be worth looking at to see how it does the  export/delete stuff:
https://github.com/danmarsden/moodle-plagiarism_urkund/blob/MOODLE_400_STABLE/classes/privacy/provider.php

The lang string "privacy:metadata:aicc:externalpurpose" or the external location stuff should be extended a bit to explain exactly "what" information is sent to the external service - eg the student file is sent, but what else is sent to the external system? eg  username/email, firstname, lastname - any other user identifying information that should be stated?

FYI - We don't always block plugins db approval on missing delete/export functions in the privacy api but it is important for some organisations that might want to use your service.

**Comment by mattan-d** [comment]
@danmarsden Fix missing delete/export functions.
Can you check again please?
