### ISSUE TITLE
missing parameter validation and security/access checks in webservice function

### ISSUE THREAD

**Issue by danmarsden** [mattan-d/moodle-plagiarism_originality#5]
The create_report() function appears to allow anonymous users to make calls to the function and it does not perform parameter validation or security/capability checks.

Please take a look at the docs here for information on what should be added there:
https://moodledev.io/docs/apis/subsystems/external/writing-a-service#parameter-validation

note this is a blocker for plugins db approval.

**Comment by mattan-d** [comment]
Add parameter validation and security/capability checks to create_report() function
