### ISSUE TITLE
it's tidier to delete files rather than leaving empty files in place

### ISSUE THREAD

**Issue by danmarsden** [mattan-d/moodle-plagiarism_originality#6]
files like install.php, uninstall.php, access.php are all optional files, - if you don't implement anything in these files, it's slightly cleaner to delete them.

not a blocker for approval - just a suggestion, feel free to ignore and close if you want! :-)

**Comment by mattan-d** [comment]
Remove unnecessary optional files (install.php, uninstall.php).
