### ISSUE TITLE
please don't call curl_init() directly

### ISSUE THREAD

**Issue by danmarsden** [mattan-d/moodle-plagiarism_originality#8]
Please don't initate curl_init() directly but use Moodle's own "curl" class which is a wrapper on PHP's curl functions.

The internal Curl wrapper takes care of some security rules and many organisations put their moodle site behind a web proxy and the internal curl wrapper takes care of this for you. 

Unfortunately it's not all that well documented, so the best way to work out how it's used is to search the existing Moodle codebase for the use of the internal Curl wrapper.

not a blocker for approval, but using the internal curl wrapper improves security and also prevents your plugin from breaking when a Moodle site is behind a web proxy

**Comment by mattan-d** [comment]
Use Moodle's internal Curl wrapper instead of directly using curl_init()
