### ISSUE TITLE
missing lang string on settings page

### ISSUE THREAD

**Issue by danmarsden** [mattan-d/moodle-plagiarism_originality#9]
I'm getting this warning on the settings page:

Invalid get_string() identifier: 'default_settings_assignments' or component 'plagiarism_originality'. Perhaps you are missing $string['default_settings_assignments'] = ''; in /plagiarism/originality/lang/en/plagiarism_originality.php?

**Comment by mattan-d** [comment]
Fix: Resolve "Invalid get_string() identifier" warning on settings page.
